### ISSUE TITLE
Don't prefix library name with "l"

### ISSUE THREAD

**Issue by nemequ** [felipe-lavratti/vala-unittests-cmake#12]
The library name should be my_project, not lmy_project.  CMake will add a "lib" prefix on appropriate platforms anyways, and people would otherwise have to use -llmy_project when linking against your library.

**Comment by flplv** [comment]
I got conflict by having same target name twice in the CMakeLists.txt, since 'my_project' is already the target name of the final binary. I'll try to rename it after I get issue #10 fixed. 

ps: Thanks for all your suggestions.

**Comment by flplv** [comment]
Yes, I got conflicting targets even with multiple CMakeLists.txt in the tree. What name should I use here instead?
https://github.com/felipe-lavratti/vala-unittests-cmake/blob/master/src_lib/CMakeLists.txt#L21

**Comment by nemequ** [comment]
I can think of two better solutions:
- Include the API version in the name.  This is [what Squash does](https://github.com/quixdb/squash/blob/master/squash/CMakeLists.txt#L64), and it's not a bad idea.
- Use whatever you want for the name of one of them (e.g., libmy_project), then use the OUTPUT_NAME target property to make the filename correct.  AFAIK something like `set_target_properties(libmy_project PROPERTIES OUTPUT_NAME my_project)` should do the trick.

**Comment by nemequ** [comment]
If you go with the second option you should adjust the comment on line 13 of the top level CMakeLists.txt, as the API version will not be included in the library name.

**Comment by nemequ** [comment]
Fixed when you added the _ prefix, then you added the API version, then I removed the _ prefix.
