### ISSUE TITLE
Review src_lib / src_main tree organisation

### ISSUE THREAD

**Issue by flplv** [felipe-lavratti/vala-unittests-cmake#21]
I am still not happy with this tree organisation, currently:
- `src_lib` has vala files to build a executable, not a _public_ library, it is compiled into a lib just to avoid "file_name.vala" duplication and compilation duplication on the targets.
- `src_main` has the main function, that is not tested.

What do you think of the following organisation proposal:
- Use `src_lib` to **really** make a public library, with public ".h", ".so" and ".vapi".  
  Rename `src_main` to `src`, and add to it all executable files.
- In the `tests/CMakeLists.txt`, instead of linking the `libmy-project-0.1.a` we recompile all .vala source (except main.vala) from `src`?

**Comment by nemequ** [comment]
The right way to do that would really be to make an internal static library, then link to that in the unit tests.  In other words, you woould _want_ to link the executable and unit tests against `libmy-project-0.1.a` (but not `libmy-project-0.1.so`, which is what it currently does).

What I would suggest is a `my-project/` directory which builds a shared library by default, but separates everything in the CMakeLists.txt so you can easily comment out (or remove) most of the code if you don't want a public library.  You would probably also need to change a variable or two, but with proper comments it shouldn't be difficult.

In the directories containing the tests and the executable (which I would probably call "utils" or "cli" or something similar), I don't think you actually need to do anything different.  You just specify the library name, CMake should be able to handle whether to link statically or not.

As a template project, I do think it is important to preserve the ability to generate a shared library.  There is a lot of boilerplate necessary for a shared library that you don't really need for an executable, and it's hard to get right, which makes it important to have a decent template to start from.  That said, if you prefer I can always just fork the project and you could simplify this repository.

**Comment by flplv** [comment]
Interesting, do you have an example project that shows your suggestion?

About this project, I believe it must be useful, so lets keep adding
usefulness to it :)

**Comment by nemequ** [comment]
> Interesting, do you have an example project that shows your suggestion?

Sorry, I've done it a few times for proprietary projects with autotools, but never in CMake or an open-source project.

If that's how you want to proceed I should be able to put something together without much difficulty, assuming CMake behaves (for once…)

**Comment by flplv** [comment]
It would be great!
Let me know anything I can do to help.

**Comment by nemequ** [comment]
835e7a3aae8f05d02c1ab15ca7958eddd9dab172 explains how to switch from a shared library to a static one.

**Comment by flplv** [comment]
Closing since source tree is in a better shape now.
