### ISSUE TITLE
Replace build.sh with configure-cmake, remove clean.sh

### ISSUE THREAD

**Issue by nemequ** [felipe-lavratti/vala-unittests-cmake#4]
Instead of some custom scripts, it would be better to provide a more standard build experience.

My [configure-cmake](https://github.com/nemequ/configure-cmake/) project would make a good replacement for build.sh since it provides an interface anyone familiar with autotools would be comfortable with, but I'd actually rather see nothing than build.sh.

For clean.sh, `make clean` should pretty much do what you want.  Also, there is `git clean -Xdf`, though that will depend on a proper .gitignore.

**Comment by flplv** [comment]
Fixed in 100cee7288370b587b8f0a2ea70361d74b2046fb
